name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Pull Latest Code
      run: |
        cd /home/lucifer/RecipeStore
        git fetch --all
        git reset --hard origin/main

    - name: Install Dependencies
      run: |
        cd /home/lucifer/RecipeStore
        npm install

    - name: Build Application
      run: |
        cd /home/lucifer/RecipeStore
        npm run build

    - name: Restart Application
      run: |
        cd /home/lucifer/RecipeStore
        pm2 stop RecipeStore || true
        pm2 start backend/dist/server.js --name RecipeStore
